version: "2.0"
services:
    askgrieves:
        build: .
        expose:
            - "8000"
        restart: unless-stopped
        volumes:
            - ./db.sqlite3:/data
            - static:/app/staticfiles
    nginx:
        image: nginx:1.18-alpine
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - static:/static
        ports:
            - "80:80"
        depends_on:
            - askgrieves
        restart: unless-stopped
volumes:
    static:
