version: '3'

services:
  web:
    build: ./a_brief_history_of_web
    command: bash -c "python a_brief_history_of_web/manage.py migrate && python a_brief_history_of_web/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"