version: '3'
volumes:
  postgres_volume:
services:
  postgres:
      container_name: friendly_frogs_postgres
      image: postgres:11
      volumes:
        - postgres_volume:/var/lib/postgresql/data/
      env_file:
        - .env
      ports:
        - "5432:5432"