
repos: 
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
    -   id: flake8
        exclude: .cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox
        args: [--max-line-length=119, --isolated]

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v1.2.3
#     hooks:
#     - id: flake8
#       exclude: .cache,.venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox
#       args: [--max-line-length=119, --isolated]
