version: '3'

services:
    db:
        image: postgres
        restart: always
        env_file:
            - web-variables.env
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        stdin_open: true
        tty: true
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - web-variables.env