
version: '3.3'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./backend/Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    expose: 
      - 8000
    env_file:
      - ./backend/django.env.prod
    depends_on: 
      - db
    restart: unless-stopped
  angular:
    container_name: angular
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - '/app/node_modules'
      - static_volume:/home/app/web/static
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
    depends_on: 
      - django
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
    env_file:
      - ./backend/db.env.prod


volumes:
  postgres_data:
  static_volume: